version: '3.8'

services:
  postgres:
    image: postgres:14.4
    restart: always
    environment:
          - POSTGRES_DB=project-x
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
    ports:
          - '5433:5433'
    volumes: 
          - ./postgres-data:/var/lib/postgresql/data
 